api call tweaks: standardize the screenshot, mhtml and raw dom api calls
webrecorder/autobrowser pull request #52
Opened 2019-05-29 01:03 UTC by ikreymer

also store 'timestamp' of current page, using either Memento-Datetime or wbinfo.timestamp headers (for api usage)

2019-05-29 20:12 UTC, N0taN3rd requested changes
Looks good overall. Small things plus `./scripts/format.sh` :)

2019-05-29 20:12 UTC, N0taN3rd commented on autobrowser/tabs/basetab.py
> +        content_type = 'application/json',
```suggestion
        content_type: str = 'application/json',
```

2019-05-29 20:12 UTC, N0taN3rd commented on autobrowser/tabs/basetab.py
> +        :param headers: content-type to be used with the data
```suggestion
        :param content_type: content-type to be used with the data
```

2019-05-29 20:12 UTC, N0taN3rd commented on autobrowser/tabs/crawlerTab.py
> +    def memento_header_to_timestamp(self, memento_dt):
Perhaps it would be simplest to move the logic of setting the `_timestamp` instance property into this function

```suggestion
    def timestamp_from_response(self, response: Response) -> None:
        memento_dt = response.headers.get("Memento-Datetime")
        ....
        self._timestamp = dt.strftime('%Y%m%d%H%M%S')
        ....
```

Otherwise I think this function is best home is Helper with signature
```python
def memento_header_to_timestamp(memento_dt: Optional[str]) -> str:
```

Since it is likely the timestamp retrieved by `BaseTab.post_behavior_run` should also be converted (unless I have forgotten the format of `window.wbinfo.timestamp`)

Also could you add a quick doc string to method.

2019-06-08 02:41 UTC, ikreymer commented on autobrowser/tabs/crawlerTab.py
> +    def memento_header_to_timestamp(self, memento_dt):
Renamed to set_timestamp_from_response as suggested and added docstring.
Removed checking for wbinfo to avoid dependency on wombat (which should set Memento-Datetime anyway). If no Memento-Datetime, just use current UTC timestamp.

2019-06-08 02:42 UTC, merged